picture_archive:
    archive:
        base_directory: '%picture_archive.archive.base_directory%'
        supported_types:
            image:
                - "/image\\//i"
                - "application/x-iso9660-image"
            video:
                - "video/mp4"
                - "video/quicktime"
                - "video/x-matroska"
                - "video/x-ms-asf"
                - "video/x-msvideo"

    import:
        base_directory: '%picture_archive.import.base_directory%'
        failed_directory: '%picture_archive.import.failed_directory%'
        minimum_fileage: 180

    tools:
        image_info: '%picture_archive.tool.image.info%'
