services:
  picture_archive.component.configuration:
    class: PictureArchiveBundle\Component\Configuration
    calls:
      - [ setArchiveBaseDirectory, ["%picture_archive.archive.base_directory%"] ]
      - [ setArchiveFiletypeSubdirectory, ["%picture_archive.archive.filetype_subdirectory%"] ]
      - [ setImportBaseDirectory, ["%picture_archive.import.base_directory%"]]
      - [ setImportFailedDirectory, ["%picture_archive.import.failed_directory%"]]
      - [ setImportMinimumFileAge, ["%picture_archive.import.minimum_fileage%"]]
      - [ setImportSupportedTypes, ["%picture_archive.import.supported_types%"]]
      - [ setTools, ["%picture_archive.tools%"]]

  picture_archive.component.filepath_generator:
    class: PictureArchiveBundle\Component\FilepathGenerator
    arguments:
      - "@picture_archive.component.configuration"

  picture_archive.component.file_system.flat_loader:
    class: PictureArchiveBundle\Component\FileSystem\FlatLoader
    arguments:
      - "@picture_archive.file.hash"
      - "@picture_archive.image.info"

  picture_archive.component.file_system.recursive_loader:
    class: PictureArchiveBundle\Component\FileSystem\RecursiveLoader
    arguments:
      - "@picture_archive.file.hash"
      - "@picture_archive.image.info"

  picture_archive.import:
    class: PictureArchiveBundle\Service\Import
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@event_dispatcher"
      - "@picture_archive.import.file_runner"
      - "@picture_archive.import.file_processor"
      - "@picture_archive.import.analyser"
      - "@picture_archive.component.configuration"
      - "@picture_archive.component.filepath_generator"

  picture_archive.import.file_runner:
    class: PictureArchiveBundle\Service\Import\FileRunner
    arguments:
      - "@picture_archive.component.configuration"
      - "@picture_archive.component.file_system.flat_loader"

  picture_archive.import.analyser:
    class: PictureArchiveBundle\Service\Import\Analyser
    calls:
      - [ addAnalyser, ["@picture_archive.import.analyser.file_min_age"]]
      - [ addAnalyser, ["@picture_archive.import.analyser.file_min_age"]]
      - [ addAnalyser, ["@picture_archive.import.analyser.file_exixts"]]
      - [ addAnalyser, ["@picture_archive.import.analyser.media_date_isset"]]

  picture_archive.import.analyser.file_min_age:
    class: PictureArchiveBundle\Service\Import\Analyser\FileMinAge
    arguments:
      - "@picture_archive.component.configuration"

  picture_archive.import.analyser.mime_type:
      class: PictureArchiveBundle\Service\Import\Analyser\MimeType
      arguments:
        - "@picture_archive.component.configuration"

  picture_archive.import.analyser.file_exixts:
    class: PictureArchiveBundle\Service\Import\Analyser\FileExists
    arguments:
      - "@picture_archive.component.configuration"
      - "@picture_archive.file.hash"
      - "@=service('doctrine.orm.default_entity_manager').getRepository('PictureArchiveBundle:MediaFile')"

  picture_archive.import.analyser.media_date_isset:
    class: PictureArchiveBundle\Service\Import\Analyser\MediaDateIsset

  picture_archive.import.report:
      class: PictureArchiveBundle\Service\Import\Report
      arguments:
            - "@picture_archive.component.configuration"
      tags:
        - { name: kernel.event_listener, event: picture-archive.import.start, method: startImport }
        - { name: kernel.event_listener, event: picture-archive.import.analyse.failed, method: importFile }
        - { name: kernel.event_listener, event: picture-archive.import.save.failed, method: importFile }
        - { name: kernel.event_listener, event: picture-archive.import.success, method: importFile }
        - { name: kernel.event_listener, event: picture-archive.import.error, method: importFile }
        - { name: kernel.event_listener, event: picture-archive.import.finish, method: finishImport }


  picture_archive.import.file_processor:
    class: PictureArchiveBundle\Service\Import\FileProcessor
    arguments:
      - "@picture_archive.component.configuration"

  picture_archive.import.failed_handler:
    class: PictureArchiveBundle\Service\Import\FailedHandler
    arguments:
          - "@picture_archive.component.configuration"
    tags:
      - { name: kernel.event_listener, event: picture-archive.import.analyse.failed, method: moveFile }
      - { name: kernel.event_listener, event: picture-archive.import.save.failed, method: moveFile }
      - { name: kernel.event_listener, event: picture-archive.import.error, method: moveFile }


  picture_archive.file.scanner:
    class: PictureArchiveBundle\Util\FileScanner


  picture_archive.file.hash:
    class: PictureArchiveBundle\Util\FileHash\Md5

  picture_archive.image.info:
    class: PictureArchiveBundle\Util\ImageExif
    arguments:
      - "%picture_archive.tool.image.info%"

  picture_archive.indexer.file_runner:
    class: PictureArchiveBundle\Service\Indexer\FileRunner
    arguments:
      - "@picture_archive.component.configuration"
      - "@picture_archive.component.file_system.recursive_loader"

  picture_archive.indexer.statistics:
    class: PictureArchiveBundle\Service\Index\Stats
    arguments:
      - "@doctrine.orm.entity_manager"

  picture_archive.indexer:
    class: PictureArchiveBundle\Service\Indexer
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@picture_archive.component.configuration"
      - "@picture_archive.indexer.file_runner"
