<?php

namespace PictureArchiveBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use PictureArchiveBundle\Entity\File;

/**
 * FilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $hash
     * @return ArrayCollection
     */
    public function findByHash($hash)
    {
        return new ArrayCollection($this->findBy(array('hash' => $hash)));
    }

    /**
     * @param string $filepath
     * @return File|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByFilepath($filepath)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM PictureArchiveBundle\:File f WHERE f.filepath = :path'
            );
        $query->setParameter('path', $filepath);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    /**
     *
     */
    public function removeAll()
    {
        $connection = $this->getEntityManager()->getConnection();
        $connection->executeUpdate($connection->getDatabasePlatform()->getTruncateTableSql('files'));
    }

    /**
     * @return ArrayCollection
     */
    public function findConflictedHashes()
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder();

        $query = $qb->select('f.hash')
            ->from('PictureArchiveBundle\:File', 'f')
            ->andWhere('f.status = :status')
            ->addGroupBy('f.hash')
            ->andHaving('count(f.hash) > 1')
            ->addOrderBy('f.mediaDate')
            ->setParameter(':status', File::STATUS_CONFLICT)
            ->getQuery();

        $result = new ArrayCollection();

        try {
            foreach ($query->execute() as $data) {
                $result->offsetSet($data['hash'], $this->findByHash($data['hash']));
            }

        } catch (\Doctrine\ORM\NoResultException $e) {
            // do nothing
        }
        return $result;
    }

    /**
     * @return int
     */
    public function countAll()
    {
        $query = $this->getEntityManager()->createQuery('SELECT COUNT(f.id) FROM PictureArchiveBundle\:File f');

        return (int)$query->getSingleScalarResult();
    }

    /**
     * @return array
     */
    public function countByType()
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder();

        $query = $qb->select('f.mimeType, count(f.id) as amount')
            ->from('PictureArchiveBundle\:File', 'f')
            ->addGroupBy('f.mimeType')
            ->addOrderBy('f.mimeType')
            ->getQuery();

        return $query->getArrayResult();
    }
}
